[workspace]
members = ["core", "cli", "web"]
resolver = "2"

[profile.release]
# Tell `rustc` to optimize for small code size.
# opt-level = "s"
debug = true
lto = true
codegen-units = 1
panic = "abort"