[package]
name = "magnificence-oxidized-chess"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
rustyline = "8.2.0"
lazy_static = "1.5.0"
strum = "0.26"
strum_macros = "0.26"