[package]
name = "engine_core"
version = "0.1.0"
edition = "2021"

[lib]
name = "engine_core"
path = "src/lib.rs"

[dependencies]
lazy_static = "1.5.0"
strum = "0.26"
strum_macros = "0.26"
num = "0.4"
num-derive = "0.4"
num-traits = "0.2"
rand = "0.8.5"
once_cell = "1.19.0"
rand_pcg = "0.3.1"